---

services:
  notion-backup:
    build:
      context: .
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: notion-backup
    restart: unless-stopped
    entrypoint: ["python", "notion_export.py"]
    environment:
      - NOTION_API_TOKEN=${NOTION_API_TOKEN}
      - EXPORT_PATH=${CONTAINER_EXPORT_PATH}
      - B2_KEY_ID=${B2_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME}
      - B2_ENDPOINT_URL=${B2_ENDPOINT_URL}
      - BACKUP_METHODS=${BACKUP_METHODS}
      - BACKUP_INTERVAL=${BACKUP_INTERVAL}
      - BACKUP_TIME=${BACKUP_TIME}
      - TIMEZONE=${TIMEZONE}
    volumes:
      - ${HOST_EXPORT_PATH}:${CONTAINER_EXPORT_PATH}

      
