FROM python:3.11-slim

WORKDIR /app

# Copy requirements.txt first for better caching
COPY requirements-webgui.txt .
RUN pip install --no-cache-dir -r requirements-webgui.txt

# Copy the application code
COPY webgui.py /app
COPY templates /app/templates
COPY static /app/static

CMD ["python", "webgui.py"]
